spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: petspa
    password: swd392

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#JPA settings    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  jpa.hibernate.ddl-auto: create