spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_spa?allowPublicKeyRetrieval=true&useSSL=false
    username: sa
    password: 12345

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#JPA settings    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  jpa.hibernate.ddl-auto: create